### ISSUE TITLE
Set custom color feature

### ISSUE THREAD

**Issue by Neutrovertido** [demiskp/custom-accent-colors#18]
I think adding an option where you can pick a hex color would make the extension 2x as good. This is very much a feature request.

**Comment by dimitriskprs** [comment]
Hey @Neutrovertido, unfortunately this feature is not as easy to implement as it might seem, because for the Shell Theming option to work it would require me to compile a Gnome Shell Theme for every possible hex value, right now the Extension provides 18 custom Gnome Shell Themes (stored in the resources directory) , 1 for every accent color and every gnome version that the extension supports (43 and 44).

**Comment by Neutrovertido** [comment]
then maybe expanding the color options could do as well, colors like light blue, cyan, etc

**Comment by dimitriskprs** [comment]
Maybe I'll work on it for v7, I might add more colors from [this pallete](https://developer.gnome.org/hig/reference/palette.html).

**Comment by Neutrovertido** [comment]
oh, that'd make for a great improvement

**Comment by ehlvg** [comment]
Hey, that would be really great,+1! Also I want to suggest a feature for previewing the color without applying it, like it's in Ubuntu, but right in the menu of the extension if it's possible

**Comment by dimitriskprs** [comment]
@bulkabuka unfortunately, I don't think there's a way to do that using a gnome extension.

**Comment by CloudyChris** [comment]
> Hey @Neutrovertido, unfortunately this feature is not as easy to implement as it might seem, because for the Shell Theming option to work it would require me to compile a Gnome Shell Theme for every possible hex value, right now the Extension provides 18 custom Gnome Shell Themes (stored in the resources directory) , 1 for every accent color and every gnome version that the extension supports (43 and 44).

Just a dumb question, since I have little experience with gnome extensions... can you compile on demand? Like, sure, it will take time, but can you get a hex value as input and when hitting apply just compile a theme then and apply it? I'm just asking if it's possible. I might give it a try myself in the future...

Also on the gnome-extensions page someone said the extension doesn't work on 44.3. Can that be due to some other customizations the user made (like manually installed themes and such?)

**Comment by ikeofkc** [comment]
https://developer.gnome.org/hig/reference/palette.html

Unfortunately there's no violet or any cooler hue of purple in gnome's palette.  Does that mean it would not be considered?
