### ISSUE TITLE
Need stronger difference between off and on gray toggles

### ISSUE THREAD

**Issue by Thatoo** [demiskp/custom-accent-colors#33]
Hello,

The difference of grey is very light between a "toggle off" and a "toggle on" so the color doesn't help, only the position.
![image](https://github.com/dimitriskp22/custom-accent-colors/assets/464782/ca45ca70-8467-428e-a314-72fd17efbcf9)

I would suggest the "toggle on" to be of the same color than the highlight color 

![image](https://github.com/dimitriskp22/custom-accent-colors/assets/464782/ec8a745c-d939-4801-ba96-50c44bc55161)

**Comment by dimitriskprs** [comment]
as I've said in #27 , I plan to change some of the accent colors to make everything clearer at some point, the gray accent color will be one of the ones that I'll change

**Comment by Thatoo** [comment]
Could we help in any way?
Would you accept PR?

**Comment by dimitriskprs** [comment]
the harder part is finding colors from the Gnome Palette (https://developer.gnome.org/hig/reference/palette.html) that look good and are not harming readability etc, after finding them, implementing them is very easy for me, if someone has the time to try to do it I would happily accept their PR, otherwise I'll do it myself in the coming weeks alongside Gnome 46 support :)

**Comment by ghost** [comment]
I liked grey accent : ( now its replaced by brown. Oh well....
