### ISSUE TITLE
Wallpaper accent color?

### ISSUE THREAD

**Issue by HironTez** [demiskp/custom-accent-colors#36]
Hi. What do you think about adding a function to extract the accent color from a current desktop wallpaper automatically? It can be easily extracted using the 'node-vibrant' library.

```js
import Vibrant from "node-vibrant";
const colors = await Vibrant.from(wallpaper).getPalette();
const accentColor = colors.LightVibrant;
```

Sorry for the duplicate, just wanted to show an easy solution for this.

**Comment by dimitriskprs** [comment]
hey @HironTez , that's indeed an easy way to get the accent color from the wallpaper, but the problem is that for the gnome shell (not the gtk apps) to use this color, the entire gnome-shell.css theme must be recompiled. the extension currently ships with 8 gnome shell themes (one for every accent color).

**Comment by HironTez** [comment]
Thank you for the reply! Yeah, looks like that's a big problem. Sorry for bothering you

**Comment by dimitriskprs** [comment]
you didn't bother me at all, any suggestion is always welcome even if it doesn't get implemented in the end :)
